
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/linuxbrew/.linuxbrew/opt/node@24/bin/"
      - "/home/linuxbrew/.linuxbrew/bin/"
      - "/home/linuxbrew/.linuxbrew/sbin/"
      - "/home/marcos/.bun/bin/"
      - "/home/marcos/.local/bin/"
      - "/home/marcos/bin/"
      - "/usr/lib64/ccache/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/usr/local/sbin/"
      - "/bin/"
    searched_directories:
      - "/home/linuxbrew/.linuxbrew/opt/node@24/bin/uname"
      - "/home/linuxbrew/.linuxbrew/bin/uname"
      - "/home/linuxbrew/.linuxbrew/sbin/uname"
      - "/home/marcos/.bun/bin/uname"
      - "/home/marcos/.local/bin/uname"
      - "/home/marcos/bin/uname"
      - "/usr/lib64/ccache/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/linuxbrew/.linuxbrew/opt/node@24/bin"
        - "/home/linuxbrew/.linuxbrew/bin"
        - "/home/linuxbrew/.linuxbrew/sbin"
        - "/home/marcos/.bun/bin"
        - "/home/marcos/.local/bin"
        - "/home/marcos/bin"
        - "/home/marcos/.local/share/../bin"
        - "/usr/lib64/ccache"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/usr/local/sbin"
  -
    kind: "message-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.18.16-200.fc43.x86_64 - x86_64
...
